# Generated by Django 5.2.11 on 2026-03-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_garment_options_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='display_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='style',
            new_name='tagline',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
