# Generated by Django 5.2.11 on 2026-03-04 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_transactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('gift', 'Gift'), ('lend', 'Lend')], max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='pending', max_length=100)),
                ('message', models.CharField(max_length=250)),
                ('points_exchanged', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to=settings.AUTH_USER_MODEL)),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.garment')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
