# Generated by Django 5.2.11 on 2026-03-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_transaction_delete_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('borrowed', 'Borrowed'), ('gifted', 'Gifted')], default='available', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('borrowed', 'Borrowed'), ('gifted', 'Gifted')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('lend', 'Lend'), ('gift', 'Gift')], max_length=100),
        ),
    ]
